### ISSUE TITLE
[Feature-Request] Benchmark Performance/Effectiveness of Different Build Flags

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzer-test-suite#114]
It is unclear which build flags are best for fuzzing. libFuzzer (apparently) recommends [-O1](https://llvm.org/docs/LibFuzzer.html#fuzzer-usage) while AFL automatically uses [-O3 -funroll-loops](https://github.com/mirrorer/afl/search?utf8=%E2%9C%93&q=cc_params%5Bcc_par_cnt%2B%2B%5D+%3D+%22-O3%22%3B&type=)

It would be awesome to have data on which build options are best. 
Would it be possible to have a benchmark that compared engines on fuzz targets built using different flags?

**Comment by kcc** [comment]
With the recent Matt's changes in Clang O1/O2 may become more friendly to fuzzing than it was before. 

+1, it would be nice to have a fresh experiment (O0 vs O1 vs O2 vs O3), 
but we will need to count the iterations, not wall clock.

**Comment by morehouse** [comment]
Why iterations rather than wall clock?

**Comment by kcc** [comment]
Because O0 is *much* slower than O1, and O1 than O2, 
but we want to understand the potential from having good stuff from O0 in O2, 
not to compare the today's state.

**Comment by morehouse** [comment]
I ran quick experiments using wall clock, but it's going to take some engineering effort for me to get the framework graphing iterations instead.  So that might need to be put on hold for now.

AFL wall clock:  http://storage.googleapis.com/fuzzer-test-suite-public/afl-opt-level/index.html
libFuzzer wall clock:  http://storage.googleapis.com/fuzzer-test-suite-public/lf-opt-level/index.html
