### ISSUE TITLE
where is libFuzzingEngine-libfuzzer.a in libjpeg-turbo-07-2017

### ISSUE THREAD

**Issue by AugustusWang18** [google/fuzzer-test-suite#128]
When I ran the build.sh in libjpeg-turbo-07-2017, I got such result. But I cannot find the libFuzzingEngine-libfuzzer.a neither in SRC nor BUILD.

```
+ clang++ -O2 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp,trace-gep,trace-div -std=c++11 ../libjpeg_turbo_fuzzer.cc -I BUILD BUILD/.libs/libturbojpeg.a libFuzzingEngine-libfuzzer.a -o ..-libfuzzer
clang-4.0: error: no such file or directory: 'libFuzzingEngine-libfuzzer.a'
```

Did I run such project in a wrong way? 
```
cd fuzzer-test-suite/libjpeg-turbo-07-2017/
mkdir tmp
cd tmp
bash ../build.sh asan
```

**Comment by AugustusWang18** [comment]
@morehouse

**Comment by morehouse** [comment]
If you use the `build.sh asan` mode of building (not officially supported), the scripts expect the libFuzzer sources to be at `../Fuzzer` relative to the fuzzer-test-suite directory.

Otherwise, the recommended method is to follow the examples at https://github.com/google/fuzzer-test-suite/blob/master/tutorial/libFuzzerTutorial.md.  If you follow that method you shouldn't need to download the libFuzzer sources.

**Comment by AugustusWang18** [comment]
Thank you for your explanation.
