### ISSUE TITLE
structure-aware-fuzzing

### ISSUE THREAD

**Issue by computereasy** [google/fuzzer-test-suite#148]
Hello,

Just a quick question regarding the "structure-aware-fuzzing" note. Isn't it a variant of grammar-aware (white/grey) box fuzzing? 

[1] https://arxiv.org/pdf/1812.01197.pdf
[2]https://people.csail.mit.edu/akiezun/pldi-kiezun.pdf

**Comment by kcc** [comment]
These are very similar, but "structure" is not necessarily the same as "grammar". 
For example, [fuzzing compressed inputs](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/structure-aware-fuzzing.md#example-compression) would count as structure-aware, but probably not as grammar-aware because there is no AST. 

Our usage of e.g. [LPM](https://github.com/google/libprotobuf-mutator) is definitely very similar to grammar-aware fuzzing.

**Comment by computereasy** [comment]
I see. Thank you @kcc
