### ISSUE TITLE
Use rsync in begin-experiment.sh

### ISSUE THREAD

**Issue by morehouse** [google/fuzzer-test-suite#47]
Replace `scp` with `rsync`.  May require a startup script on the dispatcher to use `gsutils`.

**Comment by dnoursi** [comment]
This won't strictly require using a startup script, but I think it makes sense to implement both of those together in `begin-experiment`

**Comment by dnoursi** [comment]
After getting this working, I think that a single `ssh` is preferable to a startup script because `ssh` allows the local computer to see output from the dispatcher

**Comment by dnoursi** [comment]
After working some more, I feel that vanilla `rsync` seems preferable to `gsutil rsync`, primarily because of permissions. `rsync` allows selectively preserving metadata (e.g. execute permissions), but `gsutil rsync` preserves metadata in an all-or-nothing manner; if permissions are preserved, owner UID and etc are preserved as well. Vanilla `rsync` has all the desired benefits (effectively delta transfer), and could be thought of as eliminating google storage as a middleman.

**Comment by dnoursi** [comment]
Scratch that, vanilla `rsync` isn't an option
